# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designers\card_categories.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 109)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 109))
        self.name = QtWidgets.QFrame(Form)
        self.name.setGeometry(QtCore.QRect(10, 10, 551, 91))
        self.name.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.name.setObjectName("name")
        self.name_label_categories = QtWidgets.QLabel(self.name)
        self.name_label_categories.setGeometry(QtCore.QRect(10, 50, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_label_categories.setFont(font)
        self.name_label_categories.setText("")
        self.name_label_categories.setObjectName("name_label_categories")
        self.id_label_categories = QtWidgets.QLabel(self.name)
        self.id_label_categories.setGeometry(QtCore.QRect(10, 10, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.id_label_categories.setFont(font)
        self.id_label_categories.setText("")
        self.id_label_categories.setObjectName("id_label_categories")
        self.btn_del_categories = QtWidgets.QPushButton(self.name)
        self.btn_del_categories.setGeometry(QtCore.QRect(450, 50, 93, 28))
        self.btn_del_categories.setObjectName("btn_del_categories")
        self.btn_change_categories = QtWidgets.QPushButton(self.name)
        self.btn_change_categories.setGeometry(QtCore.QRect(450, 10, 93, 28))
        self.btn_change_categories.setObjectName("btn_change_categories")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_del_categories.setText(_translate("Form", "Удалить"))
        self.btn_change_categories.setText(_translate("Form", "Изменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
