# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designers\card_products.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 109)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 551, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_name = QtWidgets.QLabel(self.frame)
        self.lbl_name.setGeometry(QtCore.QRect(10, 5, 431, 31))
        self.lbl_name.setStyleSheet("")
        self.lbl_name.setText("")
        self.lbl_name.setObjectName("lbl_name")
        self.lbl_category = QtWidgets.QLabel(self.frame)
        self.lbl_category.setGeometry(QtCore.QRect(10, 50, 201, 31))
        self.lbl_category.setStyleSheet("")
        self.lbl_category.setText("")
        self.lbl_category.setObjectName("lbl_category")
        self.lbl_count_and_price = QtWidgets.QLabel(self.frame)
        self.lbl_count_and_price.setGeometry(QtCore.QRect(230, 50, 211, 31))
        self.lbl_count_and_price.setStyleSheet("")
        self.lbl_count_and_price.setText("")
        self.lbl_count_and_price.setObjectName("lbl_count_and_price")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 4, 95, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_change_products = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_change_products.setObjectName("btn_change_products")
        self.verticalLayout.addWidget(self.btn_change_products)
        self.btn_del_products = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_del_products.setObjectName("btn_del_products")
        self.verticalLayout.addWidget(self.btn_del_products)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_change_products.setText(_translate("Form", "Изменить"))
        self.btn_del_products.setText(_translate("Form", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
