# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designers\form_products.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 360)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name_product = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.lbl_name_product.setPlainText("")
        self.lbl_name_product.setObjectName("lbl_name_product")
        self.verticalLayout.addWidget(self.lbl_name_product)
        self.categoriesComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.categoriesComboBox.setObjectName("categoriesComboBox")
        self.verticalLayout.addWidget(self.categoriesComboBox)
        self.lbl_price_product = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.lbl_price_product.setObjectName("lbl_price_product")
        self.verticalLayout.addWidget(self.lbl_price_product)
        self.lbl_count_product = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.lbl_count_product.setObjectName("lbl_count_product")
        self.verticalLayout.addWidget(self.lbl_count_product)
        self.btn_add_product = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_add_product.setObjectName("btn_add_product")
        self.verticalLayout.addWidget(self.btn_add_product)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_name_product.setPlaceholderText(_translate("Form", "Наименование"))
        self.categoriesComboBox.setPlaceholderText(_translate("Form", "Выберите каегорию"))
        self.lbl_price_product.setPlaceholderText(_translate("Form", "Цена"))
        self.lbl_count_product.setPlaceholderText(_translate("Form", "Количество"))
        self.btn_add_product.setText(_translate("Form", "Создать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
