# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designers\form_category.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 95)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_name_category = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.form_name_category.setPlainText("")
        self.form_name_category.setObjectName("form_name_category")
        self.verticalLayout.addWidget(self.form_name_category)
        self.form_btn_add_category = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.form_btn_add_category.setObjectName("form_btn_add_category")
        self.verticalLayout.addWidget(self.form_btn_add_category)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление категории"))
        self.form_name_category.setPlaceholderText(_translate("Form", "Наименование"))
        self.form_btn_add_category.setText(_translate("Form", "Добавить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
