# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designers\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 9, 781, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.categories_tab2 = QtWidgets.QWidget()
        self.categories_tab2.setObjectName("categories_tab2")
        self.scrollArea = QtWidgets.QScrollArea(self.categories_tab2)
        self.scrollArea.setGeometry(QtCore.QRect(170, 6, 601, 521))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btn_add_category = QtWidgets.QPushButton(self.categories_tab2)
        self.btn_add_category.setGeometry(QtCore.QRect(0, 7, 161, 101))
        self.btn_add_category.setObjectName("btn_add_category")
        self.tabWidget.addTab(self.categories_tab2, "")
        self.products_tab = QtWidgets.QWidget()
        self.products_tab.setObjectName("products_tab")
        self.scrollAreaProducts = QtWidgets.QScrollArea(self.products_tab)
        self.scrollAreaProducts.setGeometry(QtCore.QRect(170, 10, 602, 531))
        self.scrollAreaProducts.setWidgetResizable(True)
        self.scrollAreaProducts.setObjectName("scrollAreaProducts")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 600, 529))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollAreaProducts.setWidget(self.scrollAreaWidgetContents_2)
        self.btn_add_products = QtWidgets.QPushButton(self.products_tab)
        self.btn_add_products.setGeometry(QtCore.QRect(0, 10, 161, 101))
        self.btn_add_products.setObjectName("btn_add_products")
        self.tabWidget.addTab(self.products_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add_category.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.categories_tab2), _translate("MainWindow", "Категории"))
        self.btn_add_products.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.products_tab), _translate("MainWindow", "Продукты"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
