# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 151)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.form_add_name_product = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.form_add_name_product.setObjectName("form_add_name_product")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.form_add_name_product)
        self.comboBox_categories = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_categories.setObjectName("comboBox_categories")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_categories)
        self.btn_add_product = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_add_product.setObjectName("btn_add_product")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btn_add_product)
        self.form_add_price_product = QtWidgets.QPlainTextEdit(self.formLayoutWidget)
        self.form_add_price_product.setObjectName("form_add_price_product")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.form_add_price_product)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление продукта"))
        self.form_add_name_product.setPlaceholderText(_translate("Form", "Наименование"))
        self.comboBox_categories.setPlaceholderText(_translate("Form", "Категория"))
        self.btn_add_product.setText(_translate("Form", "Добавить"))
        self.form_add_price_product.setPlaceholderText(_translate("Form", "Цена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
