# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\shop.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 9, 781, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.products_tab = QtWidgets.QWidget()
        self.products_tab.setObjectName("products_tab")
        self.data_products = QtWidgets.QTableWidget(self.products_tab)
        self.data_products.setGeometry(QtCore.QRect(170, 10, 601, 551))
        self.data_products.setObjectName("data_products")
        self.data_products.setColumnCount(3)
        self.data_products.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.data_products.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_products.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.data_products.setHorizontalHeaderItem(2, item)
        self.layoutWidget = QtWidgets.QWidget(self.products_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 7, 161, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_add = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 0, 0, 1, 1)
        self.btn_change = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_change.sizePolicy().hasHeightForWidth())
        self.btn_change.setSizePolicy(sizePolicy)
        self.btn_change.setObjectName("btn_change")
        self.gridLayout.addWidget(self.btn_change, 1, 0, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete.sizePolicy().hasHeightForWidth())
        self.btn_delete.setSizePolicy(sizePolicy)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout.addWidget(self.btn_delete, 2, 0, 1, 1)
        self.tabWidget.addTab(self.products_tab, "")
        self.categories_tab = QtWidgets.QWidget()
        self.categories_tab.setObjectName("categories_tab")
        self.tabWidget.addTab(self.categories_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.data_products.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.data_products.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Категории"))
        item = self.data_products.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Цена"))
        self.btn_add.setText(_translate("MainWindow", "Добавить"))
        self.btn_change.setText(_translate("MainWindow", "Изменить"))
        self.btn_delete.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.products_tab), _translate("MainWindow", "Продукты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.categories_tab), _translate("MainWindow", "Категории"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
